// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserStatus int32

const (
	UserStatus_INACTIVE UserStatus = 0
	UserStatus_ACTIVE   UserStatus = 1
	UserStatus_DELETED  UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "INACTIVE",
	1: "ACTIVE",
	2: "DELETED",
}

var UserStatus_value = map[string]int32{
	"INACTIVE": 0,
	"ACTIVE":   1,
	"DELETED":  2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type NewUserRequest struct {
	Email                string     `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Uuid                 string     `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=protocol.UserStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *NewUserRequest) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_INACTIVE
}

type NewUserResponse struct {
	Email                string     `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Uuid                 string     `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=protocol.UserStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NewUserResponse) Reset()         { *m = NewUserResponse{} }
func (m *NewUserResponse) String() string { return proto.CompactTextString(m) }
func (*NewUserResponse) ProtoMessage()    {}
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *NewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserResponse.Unmarshal(m, b)
}
func (m *NewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserResponse.Marshal(b, m, deterministic)
}
func (m *NewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserResponse.Merge(m, src)
}
func (m *NewUserResponse) XXX_Size() int {
	return xxx_messageInfo_NewUserResponse.Size(m)
}
func (m *NewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserResponse proto.InternalMessageInfo

func (m *NewUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *NewUserResponse) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_INACTIVE
}

func init() {
	proto.RegisterEnum("protocol.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*NewUserRequest)(nil), "protocol.NewUserRequest")
	proto.RegisterType((*NewUserResponse)(nil), "protocol.NewUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x19, 0x5c,
	0x7c, 0x7e, 0xa9, 0xe5, 0xa1, 0xc5, 0xa9, 0x45, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x22, 0x5c, 0xac, 0xa9, 0xb9, 0x89, 0x99, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10,
	0x8e, 0x90, 0x10, 0x17, 0x4b, 0x69, 0x69, 0x66, 0x8a, 0x04, 0x13, 0x58, 0x10, 0xcc, 0x16, 0xd2,
	0xe1, 0x62, 0x2b, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x33, 0x12,
	0xd1, 0x83, 0x19, 0xab, 0x07, 0x32, 0x30, 0x18, 0x2c, 0x17, 0x04, 0x55, 0xa3, 0x94, 0xc9, 0xc5,
	0x0f, 0xb7, 0xa9, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x95, 0x56, 0x56, 0x69, 0x19, 0x73, 0x71, 0x21,
	0x44, 0x85, 0x78, 0xb8, 0x38, 0x3c, 0xfd, 0x1c, 0x9d, 0x43, 0x3c, 0xc3, 0x5c, 0x05, 0x18, 0x84,
	0xb8, 0xb8, 0xd8, 0xa0, 0x6c, 0x46, 0x21, 0x6e, 0x2e, 0x76, 0x17, 0x57, 0x1f, 0xd7, 0x10, 0x57,
	0x17, 0x01, 0x26, 0x23, 0x3f, 0x2e, 0x16, 0x90, 0x26, 0x21, 0x37, 0x2e, 0xde, 0xe0, 0xd2, 0xa4,
	0xdc, 0xcc, 0x12, 0xa8, 0x6b, 0x85, 0x24, 0x10, 0x76, 0xa1, 0x06, 0x95, 0x94, 0x24, 0x16, 0x19,
	0x88, 0xd7, 0x94, 0x18, 0x9c, 0x98, 0x02, 0x18, 0x93, 0xd8, 0xc0, 0xf2, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x35, 0x74, 0x39, 0x1e, 0x7c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	SubmitNewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) SubmitNewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error) {
	out := new(NewUserResponse)
	err := c.cc.Invoke(ctx, "/protocol.User/SubmitNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	SubmitNewUser(context.Context, *NewUserRequest) (*NewUserResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_SubmitNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SubmitNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.User/SubmitNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SubmitNewUser(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitNewUser",
			Handler:    _User_SubmitNewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
